### ISSUE TITLE
Test failures don't cause overall test failure

### ISSUE THREAD

**Issue by arr28** [SanchoGGP/ggp-base#220]
[Build 35](https://snap-ci.com/SanchoGGP/ggp-base/branch/develop/logs/defaultPipeline/35/All?back_to=build_history) reports success, but actually one of the UTs failed.

```
java.lang.OutOfMemoryError: Java heap space
at java.util.Arrays.copyOf(Arrays.java:3332)
at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:137)
at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:121)
at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:421)
at java.lang.StringBuilder.append(StringBuilder.java:136)
at org.ggp.base.util.propnet.polymorphic.PolymorphicPropNet.toString(PolymorphicPropNet.java:819)
at org.ggp.base.util.propnet.polymorphic.PolymorphicPropNet.renderToFile(PolymorphicPropNet.java:842)
at org.ggp.base.util.statemachine.implementation.propnet.forwardDeadReckon.ForwardDeadReckonPropnetStateMachine.initialize(ForwardDeadReckonPropnetStateMachine.java:1893)
at org.ggp.base.test.FDRPStateMachineTests.testPropNetSizes(FDRPStateMachineTests.java:235)
```

Ant new that the test failed, but it didn't report an overall failure as a result.  However, that isn't what we want.  I single UT failure should trigger a failed build error (otherwise we'll never notice).

```
    [junit] 	at org.ggp.base.player.gamer.statemachine.sancho.ThreadControl.registerSearchThread(ThreadControl.java:113) [bin/:?]
    [junit] 	at org.ggp.base.player.gamer.statemachine.sancho.GameSearcher.run(GameSearcher.java:297) [bin/:?]
    [junit] 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]
    [junit] 
    [junit] Test org.ggp.base.test.AllTests FAILED

junitreport:
[junitreport] Processing /var/snap-ci/repo/junit/TESTS-TestSuites.xml to /tmp/null2013854340
[junitreport] Loading stylesheet jar:file:/opt/local/ant/apache-ant-1.9.4/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 626ms
[junitreport] Deleting: /tmp/null2013854340

BUILD SUCCESSFUL
Total time: 6 minutes 16 seconds
Command ant clean build AllTests junitreport exited successfully with status 0. Took 6 minutes 17 seconds.
```

**Comment by arr28** [comment]
Fixed.  Tested on Windows.
