### ISSUE TITLE
OutOfMemoryError solving sudoku on snap-ci

### ISSUE THREAD

**Issue by arr28** [SanchoGGP/ggp-base#244]
Steve,

Since your big commit of the perf. stuff you've been doing, the tests have been failing with OutOfMemoryError.

- From build 93...

```
AllTests:
    [mkdir] Created dir: /var/snap-ci/repo/junit
    [junit] Running org.ggp.base.test.AllTests
    [junit] 
    [junit] Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "AsyncAppender-AsyncMatchWrapper"
    [junit] 
    [junit] Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "AsyncAppender-AsyncMatchStatsWrapper"
```

And build 94...

```
AllTests:
    [mkdir] Created dir: /var/snap-ci/repo/junit
    [junit] Running org.ggp.base.test.AllTests
    [junit] 
    [junit] Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Search Processor"
    [junit] 
    [junit] Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "SystemStatsLogger"
    [junit] 
    [junit] Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "AsyncAppender-AsyncMatchStatsWrapper"
```

These are new errors which haven't been seen before on the overnights.

**Comment by arr28** [comment]
We're running out of memory trying to solve sudoku.  This looks like a regression (although could yet prove to be intermittent, I suppose).  Diffing the logs from the builds 90 (last good) and 93 (first that failed with OutOfMemory), there don't seem to be many material differences.

The successful case solves sudoku in 2s despite running at <30% of the number of simulations/second (during metagaming) that the failing case does.  The only thing that I slightly wonder about is...

```
INFO  dDeadReckonPropnetStateMachine Iterations in 2500 ms with/without removal before adding: 569/568
```

...in the passing case, vs...

```
INFO  dDeadReckonPropnetStateMachine Iterations in 2500 ms with/without removal before adding: 2386/1684
```

...in the failing case.  However, it looks like the decision should (just) go the same way each time, so this is probably a red herring.

**Comment by arr28** [comment]
This does *not* appear to be related to snap-ci.  I can't solve sudoku on my fast machine either, even allowing use of all 4 cores and running with 60s/60s.  However, I get different symptoms.  Instead of running out of memory, I get...

```
22:13:19.776 - Exception in thread "Search Processor" 
22:13:19.786 - java.lang.ArrayIndexOutOfBoundsException: 65535
22:13:19.787 - 	at org.ggp.base.util.propnet.polymorphic.forwardDeadReckon.ForwardDeadReckonLegalMoveSet$ForwardDeadReckonLegalMoveSetIterator.next(ForwardDeadReckonLegalMoveSet.java:87)
22:13:19.787 - 	at org.ggp.base.util.propnet.polymorphic.forwardDeadReckon.ForwardDeadReckonLegalMoveSet$ForwardDeadReckonLegalMoveSetIterator.next(ForwardDeadReckonLegalMoveSet.java:1)
22:13:19.787 - 	at org.ggp.base.util.statemachine.implementation.propnet.forwardDeadReckon.PartitionedChoiceStateMachineFilter.nextFilteredMove(PartitionedChoiceStateMachineFilter.java:189)
22:13:19.787 - 	at org.ggp.base.player.gamer.statemachine.sancho.TreeNode.expandInternal(TreeNode.java:3186)
22:13:19.787 - 	at org.ggp.base.player.gamer.statemachine.sancho.TreeNode.expand(TreeNode.java:2484)
22:13:19.787 - 	at org.ggp.base.player.gamer.statemachine.sancho.MCTSTree.selectAction(MCTSTree.java:947)
22:13:19.787 - 	at org.ggp.base.player.gamer.statemachine.sancho.MCTSTree.growTree(MCTSTree.java:780)
22:13:19.787 - 	at org.ggp.base.player.gamer.statemachine.sancho.GameSearcher.expandSearch(GameSearcher.java:766)
22:13:19.787 - 	at org.ggp.base.player.gamer.statemachine.sancho.GameSearcher.processCompletedRollouts(GameSearcher.java:945)
22:13:19.787 - 	at org.ggp.base.player.gamer.statemachine.sancho.TreeNode.rollOut(TreeNode.java:5373)
22:13:19.787 - 	at org.ggp.base.player.gamer.statemachine.sancho.MCTSTree.selectAction(MCTSTree.java:974)
22:13:19.787 - 	at org.ggp.base.player.gamer.statemachine.sancho.MCTSTree.growTree(MCTSTree.java:780)
22:13:19.787 - 	at org.ggp.base.player.gamer.statemachine.sancho.GameSearcher.expandSearch(GameSearcher.java:766)
22:13:19.787 - 	at org.ggp.base.player.gamer.statemachine.sancho.GameSearcher.run(GameSearcher.java:357)
22:13:19.787 - 	at java.lang.Thread.run(Thread.java:744)
```

(I note that the partitioned choice state machine filter is still kicking in - so it isn't that we've completely lost our special sudoku technique.)

**Comment by SteveDraper** [comment]
Yup - I broke Sudoku - ,looking at it now

**Comment by SteveDraper** [comment]
The new legal move set representation appears to have a bug in 'intersect'
which is only used by this filter

**Comment by SteveDraper** [comment]
Actually it was a bug in clear() but it influenced usage in the partitioning filter.
