### ISSUE TITLE
FDRPStateMachineTests failing

### ISSUE THREAD

**Issue by arr28** [SanchoGGP/ggp-base#245]
Steve,

All but one of the `FDRPStateMachineTests` are failing with an `ArrayIndexOutOfBoundsException`.  The failures were originally masked by some of the other problems we've seen, but I have a strong hunch that they're as a result of the big commit at the end of your week of perf..

All have the same stack.

```
java.lang.ArrayIndexOutOfBoundsException: 16777215
	at org.ggp.base.util.propnet.polymorphic.forwardDeadReckon.ForwardDeadReckonPropnetFastAnimator.getComponentValue(ForwardDeadReckonPropnetFastAnimator.java:990)
	at org.ggp.base.util.propnet.polymorphic.forwardDeadReckon.ForwardDeadReckonPropNet.getComponentValue(ForwardDeadReckonPropNet.java:288)
	at org.ggp.base.util.statemachine.implementation.propnet.forwardDeadReckon.ForwardDeadReckonPropnetStateMachine.isTerminalUnfactored(ForwardDeadReckonPropnetStateMachine.java:2510)
	at org.ggp.base.util.statemachine.implementation.propnet.forwardDeadReckon.ForwardDeadReckonPropnetStateMachine.isTerminal(ForwardDeadReckonPropnetStateMachine.java:2504)
	at org.ggp.base.util.statemachine.implementation.propnet.forwardDeadReckon.ForwardDeadReckonPropnetStateMachine.isTerminal(ForwardDeadReckonPropnetStateMachine.java:2494)
	at org.ggp.base.util.statemachine.implementation.propnet.forwardDeadReckon.ForwardDeadReckonPropnetStateMachine.isTerminal(ForwardDeadReckonPropnetStateMachine.java:2473)
	at org.ggp.base.test.FDRPStateMachineTests.testDistinctAtBeginningOfRule(FDRPStateMachineTests.java:179)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
```

And all have the same errant index: 16777215 = 0xFFFFFF.

**Comment by SteveDraper** [comment]
What do I need to run (under the debugger) to reproduce this? (as in what
Java app to invoke and with what params)

**Comment by SteveDraper** [comment]
nvm -figured it out.

**Comment by SteveDraper** [comment]
Cause was propnet splits in which the terminal prop could not be set within that split
