### ISSUE TITLE
Take a look at the new games with deliberately 'bad' GDL reps in gamemaster

### ISSUE THREAD

**Issue by SteveDraper** [SanchoGGP/ggp-base#264]
These do not seem to be in any of the available repositories, but gamemaster has a 'bad' variant of TicTacToe and one of Skirmish.  See http://gamemaster.stanford.edu/gameplayer.php?id=tictactoebad etc.

Would be interesting to see how we handle these (if at all)

**Comment by arr28** [comment]
Bear in mind that they might not be new.  It could just be their way of saving off an old bad version to make room for a replacement.

Also, before dealing with actually bad GDL, I think we need to deal with some of the forms of recursion that are legal but we can't cope with.

**Comment by arr28** [comment]
There are two "bad" games on gamemaster: tictactoebad and skirmishbad.  Each has two different copies of the GDL...

- manager.kif contains the "good" version - presumably supplied to the game manager
- player.kif contains the "bad" version - presumably to be supplied to players

## TTT

Looking at TTT, there are two classes of difference.  My wild speculation is that we'd handle these just fine.

### Duplicate legals

Some of the legal rules are duplicated, verbatim.

```
    (<= (legal ?w (mark ?x ?y))
        (true (cell ?x ?y b))
        (true (control ?w)))

    (<= (legal ?w (mark ?x ?y))
        (true (cell ?x ?y b))
        (true (control ?w)))

    (<= (legal ?w (mark ?x ?y))
        (true (cell ?x ?y b))
        (true (control ?w)))

    (<= (legal ?w (mark ?x ?y))
        (true (cell ?x ?y b))
        (true (control ?w)))
```

### Duplicate sub-goals

With a "next" rule, there are duplicate conditions, each using different variables, but specifying the same condition.

```
    (<= (next (cell ?m ?n x))
        (true (cell ?m1 ?n1 b))
        (true (cell ?m2 ?n2 b))
        (true (cell ?m3 ?n3 b))
        (true (cell ?m4 ?n4 b))
        (true (cell ?m5 ?n5 b))
        (true (cell ?m ?n b))
        (does white (mark ?m ?n)))
```

## Skirmish

Looking at Skirmish, all references to the `capturecount` base props have been removed.  Instead, the goals are calculated by looking at the number of pieces the opponent has remaining, using view props (and inverting the `scoremap` to compensate).

Again, I reckon we'd handle this just fine, but haven't tried yet.

**Comment by arr28** [comment]
We play TTTbad reliably and complete the root very quickly.  Not conclusive proof that we are treating the multiple sub-goals correctly, but I strongly suspect we are and don't plan to investigate further.

(I'll still look into skirmishbad.)

**Comment by arr28** [comment]
skirmishbad has an unsafe rule in it (apparently).  We report...

```
17:46:10.871 ! Exception in player during meta-gaming
java.lang.RuntimeException: Error in rule ( <= ( currentcount ?Player ?file ?rank ?sofar ?sofar ) ( file ?file ) ( rank ?rank ) ( role ?Player ) ( not ( colored ?file ?rank ?Player ) ) ) for variable ?sofar
	at org.ggp.base.util.gdl.model.SentenceDomainModelOptimizer.getVarDomainInRuleBody(SentenceDomainModelOptimizer.java:245) ~[bin/:?]
	at org.ggp.base.util.gdl.model.SentenceDomainModelOptimizer.propagatePossibleConstants(SentenceDomainModelOptimizer.java:169) ~[bin/:?]
	at org.ggp.base.util.gdl.model.SentenceDomainModelOptimizer.removeImpossibleConstants(SentenceDomainModelOptimizer.java:116) ~[bin/:?]
	at org.ggp.base.util.gdl.model.SentenceDomainModelOptimizer.restrictDomainsToUsefulValues(SentenceDomainModelOptimizer.java:82) ~[bin/:?]
	at org.ggp.base.util.gdl.transforms.CondensationIsolator.run(CondensationIsolator.java:136) ~[bin/:?]
	at org.ggp.base.util.propnet.polymorphic.factory.OptimizingPolymorphicPropNetFactory.create(OptimizingPolymorphicPropNetFactory.java:132) ~[bin/:?]
	at org.ggp.base.util.statemachine.implementation.propnet.forwardDeadReckon.ForwardDeadReckonPropnetStateMachine.initialize(ForwardDeadReckonPropnetStateMachine.java:1625) ~[bin/:?]
	at org.ggp.base.player.gamer.statemachine.sancho.StateMachineProxy.initialize(StateMachineProxy.java:38) ~[bin/:?]
	at org.ggp.base.player.gamer.statemachine.StateMachineGamer.metaGame(StateMachineGamer.java:204) [bin/:?]
	at org.ggp.base.player.request.grammar.StartRequest.process(StartRequest.java:70) [bin/:?]
	at org.ggp.base.player.GamePlayer.run(GamePlayer.java:111) [bin/:?]
Caused by: java.lang.IllegalArgumentException: Unsafe rule has no positive conjuncts
	at org.ggp.base.util.gdl.model.SentenceDomainModelOptimizer.getIntersection(SentenceDomainModelOptimizer.java:275) ~[bin/:?]
	at org.ggp.base.util.gdl.model.SentenceDomainModelOptimizer.getVarDomainInRuleBody(SentenceDomainModelOptimizer.java:241) ~[bin/:?]
	... 10 more
```

I'm not bothered about that.

**Comment by arr28** [comment]
Sounds very much like they plan to play SkirmishBad.  We should make sure we can cope.

**Comment by SteveDraper** [comment]
They surely need to produce a legal version first.  'bad' inefficient isn't
fine, but 'bad' illegal surely not!  We need to keep our eyes peeled for an
update for sure

**Comment by arr28** [comment]
Yep - they seem to have accepted that games with illegal GDL don't actually constitute a valid test.  We _should_ automatically detect if they check in any new games to the Stanford repository (by failing the `KnownGamesTest` which is very fast and part of the 1st stage of the snap-ci pipeline).  Closing again.
