### ISSUE TITLE
No time for transition mechanism tuning => crashes

### ISSUE THREAD

**Issue by arr28** [SanchoGGP/ggp-base#269]
I think I've seen this twice (out of 2) for Guess 2/3rds 4-player.

```
12:29:36.705 - Insufficient time remaining for transition mechanism tuning
12:29:36.706 - Disabling greedy rollouts
12:29:36.707 - Animator instance state vector size: 103
12:29:36.710 - Animator instance state vector size: 103
12:29:36.710 - Weight decay knee and scale factor: (1, 0.16666666666666666)
12:29:36.710 - Using periodic node score normalization
12:29:36.710 - Using UCB-tuned
12:29:36.710 - Early cutoff depth: 1
12:29:36.710 - This game is not suitable for local search
12:29:36.712 - MCTS iterations last turn = 0
12:29:36.712 - Encountered childless root - must re-expand
12:29:36.712 ! Exception in player
java.lang.NullPointerException
	at org.ggp.base.util.statemachine.implementation.propnet.forwardDeadReckon.ForwardDeadReckonPropnetStateMachine.getNextState(ForwardDeadReckonPropnetStateMachine.java:2856) ~[bin/:?]
	at org.ggp.base.player.gamer.statemachine.sancho.TreeNode.expandInternal(TreeNode.java:3309) ~[bin/:?]
	at org.ggp.base.player.gamer.statemachine.sancho.TreeNode.expand(TreeNode.java:2586) ~[bin/:?]
	at org.ggp.base.player.gamer.statemachine.sancho.MCTSTree.setRootState(MCTSTree.java:773) ~[bin/:?]
	at org.ggp.base.player.gamer.statemachine.sancho.GameSearcher.startSearch(GameSearcher.java:866) ~[bin/:?]
	at org.ggp.base.player.gamer.statemachine.sancho.Sancho.stateMachineMetaGame(Sancho.java:1002) ~[bin/:?]
	at org.ggp.base.player.gamer.statemachine.StateMachineGamer.metaGame(StateMachineGamer.java:208) [bin/:?]
	at org.ggp.base.player.request.grammar.StartRequest.process(StartRequest.java:70) [bin/:?]
	at org.ggp.base.player.GamePlayer.run(GamePlayer.java:111) [bin/:?]
12:29:36.740 ? [GamePlayer] java.lang.NullPointerException
	at org.ggp.base.util.statemachine.implementation.propnet.forwardDeadReckon.ForwardDeadReckonPropnetStateMachine.getNextState(ForwardDeadReckonPropnetStateMachine.java:2856)
	at org.ggp.base.player.gamer.statemachine.sancho.TreeNode.expandInternal(TreeNode.java:3309)
	at org.ggp.base.player.gamer.statemachine.sancho.TreeNode.expand(TreeNode.java:2586)
	at org.ggp.base.player.gamer.statemachine.sancho.MCTSTree.setRootState(MCTSTree.java:773)
	at org.ggp.base.player.gamer.statemachine.sancho.GameSearcher.startSearch(GameSearcher.java:866)
	at org.ggp.base.player.gamer.statemachine.sancho.Sancho.stateMachineMetaGame(Sancho.java:1002)
	at org.ggp.base.player.gamer.statemachine.StateMachineGamer.metaGame(StateMachineGamer.java:208)
	at org.ggp.base.player.request.grammar.StartRequest.process(StartRequest.java:70)
	at org.ggp.base.player.GamePlayer.run(GamePlayer.java:111)

12:29:36.741 ? [GamePlayer] An unhandled exception occurred during metagaming: org.ggp.base.player.gamer.exception.MetaGamingException: java.lang.NullPointerException
	at org.ggp.base.player.gamer.statemachine.StateMachineGamer.metaGame(StateMachineGamer.java:214)
	at org.ggp.base.player.request.grammar.StartRequest.process(StartRequest.java:70)
	at org.ggp.base.player.GamePlayer.run(GamePlayer.java:111)
Caused by: java.lang.NullPointerException
	at org.ggp.base.util.statemachine.implementation.propnet.forwardDeadReckon.ForwardDeadReckonPropnetStateMachine.getNextState(ForwardDeadReckonPropnetStateMachine.java:2856)
	at org.ggp.base.player.gamer.statemachine.sancho.TreeNode.expandInternal(TreeNode.java:3309)
	at org.ggp.base.player.gamer.statemachine.sancho.TreeNode.expand(TreeNode.java:2586)
	at org.ggp.base.player.gamer.statemachine.sancho.MCTSTree.setRootState(MCTSTree.java:773)
	at org.ggp.base.player.gamer.statemachine.sancho.GameSearcher.startSearch(GameSearcher.java:866)
	at org.ggp.base.player.gamer.statemachine.sancho.Sancho.stateMachineMetaGame(Sancho.java:1002)
	at org.ggp.base.player.gamer.statemachine.StateMachineGamer.metaGame(StateMachineGamer.java:208)
	... 2 more

12:29:36.712 ! Exception in player
java.lang.NullPointerException
	at org.ggp.base.util.statemachine.implementation.propnet.forwardDeadReckon.ForwardDeadReckonPropnetStateMachine.getNextState(ForwardDeadReckonPropnetStateMachine.java:2856) ~[bin/:?]
	at org.ggp.base.player.gamer.statemachine.sancho.TreeNode.expandInternal(TreeNode.java:3309) ~[bin/:?]
	at org.ggp.base.player.gamer.statemachine.sancho.TreeNode.expand(TreeNode.java:2586) ~[bin/:?]
	at org.ggp.base.player.gamer.statemachine.sancho.MCTSTree.setRootState(MCTSTree.java:773) ~[bin/:?]
	at org.ggp.base.player.gamer.statemachine.sancho.GameSearcher.startSearch(GameSearcher.java:866) ~[bin/:?]
	at org.ggp.base.player.gamer.statemachine.sancho.Sancho.stateMachineMetaGame(Sancho.java:1002) ~[bin/:?]
	at org.ggp.base.player.gamer.statemachine.StateMachineGamer.metaGame(StateMachineGamer.java:208) [bin/:?]
	at org.ggp.base.player.request.grammar.StartRequest.process(StartRequest.java:70) [bin/:?]
	at org.ggp.base.player.GamePlayer.run(GamePlayer.java:111) [bin/:?]
[GamePlayer] java.lang.NullPointerException
	at org.ggp.base.util.statemachine.implementation.propnet.forwardDeadReckon.ForwardDeadReckonPropnetStateMachine.getNextState(ForwardDeadReckonPropnetStateMachine.java:2856)
	at org.ggp.base.player.gamer.statemachine.sancho.TreeNode.expandInternal(TreeNode.java:3309)
	at org.ggp.base.player.gamer.statemachine.sancho.TreeNode.expand(TreeNode.java:2586)
	at org.ggp.base.player.gamer.statemachine.sancho.MCTSTree.setRootState(MCTSTree.java:773)
	at org.ggp.base.player.gamer.statemachine.sancho.GameSearcher.startSearch(GameSearcher.java:866)
	at org.ggp.base.player.gamer.statemachine.sancho.Sancho.stateMachineMetaGame(Sancho.java:1002)
	at org.ggp.base.player.gamer.statemachine.StateMachineGamer.metaGame(StateMachineGamer.java:208)
	at org.ggp.base.player.request.grammar.StartRequest.process(StartRequest.java:70)
	at org.ggp.base.player.GamePlayer.run(GamePlayer.java:111)

[GamePlayer] An unhandled exception occurred during metagaming: org.ggp.base.player.gamer.exception.MetaGamingException: java.lang.NullPointerException
	at org.ggp.base.player.gamer.statemachine.StateMachineGamer.metaGame(StateMachineGamer.java:214)
	at org.ggp.base.player.request.grammar.StartRequest.process(StartRequest.java:70)
	at org.ggp.base.player.GamePlayer.run(GamePlayer.java:111)
Caused by: java.lang.NullPointerException
	at org.ggp.base.util.statemachine.implementation.propnet.forwardDeadReckon.ForwardDeadReckonPropnetStateMachine.getNextState(ForwardDeadReckonPropnetStateMachine.java:2856)
	at org.ggp.base.player.gamer.statemachine.sancho.TreeNode.expandInternal(TreeNode.java:3309)
	at org.ggp.base.player.gamer.statemachine.sancho.TreeNode.expand(TreeNode.java:2586)
	at org.ggp.base.player.gamer.statemachine.sancho.MCTSTree.setRootState(MCTSTree.java:773)
	at org.ggp.base.player.gamer.statemachine.sancho.GameSearcher.startSearch(GameSearcher.java:866)
	at org.ggp.base.player.gamer.statemachine.sancho.Sancho.stateMachineMetaGame(Sancho.java:1002)
	at org.ggp.base.player.gamer.statemachine.StateMachineGamer.metaGame(StateMachineGamer.java:208)
	... 2 more

12:29:52.249 ? [GamePlayer] Got play message not intended for current game: ignoring.
[GamePlayer] Got play message not intended for current game: ignoring.
12:30:23.244 ? [GamePlayer] Got stop message not intended for current game: ignoring.
[GamePlayer] Got stop message not intended for current game: ignoring.
```

It eventually led to the watchdog kicking in.

Steve, please could you take a look?

**Comment by SteveDraper** [comment]
The problem is actually red-flagged earlier in the log than the section above - it's the first warning about insufficient time.  Looking at Andrew's full log from Tiltyard it is apparent that we were given 170 seconds metagaming time, but the propnet took about 190 seconds to produce (leaving less than no time to do the rest of metagaming).  As as a result the sampling loops were omitted, and when MCTS expansion started it incorrectly assumed a non-simultaneous game with non-decision nodes removed, which means it expected to find 3 roles nooping each turn, and had a very bad day when the statemachine did not agree!

I have added a 'hasAdequateSampling' boolean to the game characteristics, which is set after the sampling loop gets enough iterations to be reasonable, and should be interpreted as an indication that the recorded characteristics are unreliable.  In particular MCTSTree now requires adequate sampling before deciding it can use non-decision-node removal, and this fixes the crash.
