### ISSUE TITLE
SearchProcessor death not well handled

### ISSUE THREAD

**Issue by arr28** [SanchoGGP/ggp-base#272]
As a follow-on from #271, there are two issues...

- Firstly, we don't catch and log the exception.  Fortunately, everything that goes to stderr gets logged, so I did find this thread deatch, but I didn't spot it immediately whilst trawling for error logs.
- After SearchProcessor death, the rest of Sancho keeps running.  Eventually (10 moves later), the tree is bled dry (I think) and we return a null move.

```
23:53:42.312 - Current observed rollout score range: [1000, -100]
23:53:42.312 ?   Factor best move is NULL
[GamePlayer] java.lang.NullPointerException
	at org.ggp.base.player.gamer.statemachine.sancho.GameSearcher.getBestMove(GameSearcher.java:643)
	at org.ggp.base.player.gamer.statemachine.sancho.Sancho.stateMachineSelectMove(Sancho.java:1238)
	at org.ggp.base.player.gamer.statemachine.StateMachineGamer.selectMove(StateMachineGamer.java:248)
	at org.ggp.base.player.request.grammar.PlayRequest.process(PlayRequest.java:58)
	at org.ggp.base.player.GamePlayer.run(GamePlayer.java:111)
```

- Then we seem to recover and play apparently the only move each turn for another 9 turns or so.

**Comment by arr28** [comment]
Oh, and when assertions are turned on, it also fails to release debug tree ownership.

**Comment by arr28** [comment]
Exceptions now logged properly.  We try to keep going following an exception.  And (when assertions are turned on), we don't leak the debug tree ownership lock.
