### ISSUE TITLE
Left with GameSearcher + RolloutProcessors running

### ISSUE THREAD

**Issue by arr28** [SanchoGGP/ggp-base#274]
After exceptions in a game of guess 2/3rds 4-player (see #272), the GameSearcher + RolloutProcessor threads persist.  The GameSearcher is in state `wait` and the RolloutProcessors are all running and using up 75% of the CPU.  Many hours after the event and having played many games in between.

The Watchdog thread had problems during tidy-up but the exceptions happened after the point where the GameSearcher (and therefore RolloutProcessors) should have stopped.  (It was trying to dereference mGameCharacteristics, which may not have been set up because some parts of meta-gaming timed out.)

```
12:39:35.603 ? Watchdog liveness timer expired
12:39:35.603 ? Game aborted on watchdog expiry
12:39:35.603 ! Watchdog died unexpectedly
java.lang.NullPointerException
	at org.ggp.base.player.gamer.statemachine.sancho.Sancho.tidyUp(Sancho.java:1389) ~[bin/:?]
	at org.ggp.base.player.gamer.statemachine.sancho.Sancho.expired(Sancho.java:1357) ~[bin/:?]
	at org.ggp.base.player.gamer.statemachine.sancho.Watchdog.run(Watchdog.java:133) [bin/:?]
	at java.lang.Thread.run(Thread.java:744) [?:1.7.0_45]
```

**Comment by arr28** [comment]
Ah - this is completely because of #275.  Because we play a new game, we overwrite our references to the game searcher, etc..  When that game finished normally, it tidied up normally, leaving no references to the zombie threads.

Closing this (although not fixed yet) in favour of #275.
