### ISSUE TITLE
New game starts while old watchdog still running

### ISSUE THREAD

**Issue by arr28** [SanchoGGP/ggp-base#275]
After the 4-player 2/3rds problem, we got a whole game of Tinfoil in (just - by 30s) before the watchdog expired for2/3rds.  If the watchdog had expired in the middle of a game, we'd have done some wholly inappropriate tidy-up (like draining pools for a start).

However, the bigger problem here is that we shouldn't be starting a new game if the watchdog from a previous game is still running.  I think the new start request was accepted because the 2/3rds crashed out of meta-gaming (which I think means we don't store a game ID).  Either that or perhaps we responded in some way to the unexpected stop message from 2/3rds.

```
12:29:52.249 ? [GamePlayer] Got play message not intended for current game: ignoring.
[GamePlayer] Got play message not intended for current game: ignoring.
12:30:23.244 ? [GamePlayer] Got stop message not intended for current game: ignoring.
[GamePlayer] Got stop message not intended for current game: ignoring.
```

Either way, we did start a new game...

```
12:32:35.351 - ======================================================
12:32:35.351 - Beginning new game: tiltyard.gt_tinfoilv0.1432899142881
12:32:35.351 - Logs available at:  http://localhost:9199/localview/tiltyard.gt_tinfoilv0.1432899142881
12:32:35.362 - Looks like a game of base.gt_tinfoil
```

...and finished it...

```
12:38:57.855 - Final score: 90
12:38:57.855 - Stop the watchdog
12:38:57.855 - Watchdog terminated
12:38:57.855 - Terminating GameSearcher
12:39:01.216 - Tidy-up complete
```

...before the previous watchdog went off.

```
12:39:35.603 ! Watchdog died unexpectedly
java.lang.NullPointerException
	at org.ggp.base.player.gamer.statemachine.sancho.Sancho.tidyUp(Sancho.java:1389) ~[bin/:?]
	at org.ggp.base.player.gamer.statemachine.sancho.Sancho.expired(Sancho.java:1357) ~[bin/:?]
	at org.ggp.base.player.gamer.statemachine.sancho.Watchdog.run(Watchdog.java:133) [bin/:?]
	at java.lang.Thread.run(Thread.java:744) [?:1.7.0_45]
```

**Comment by arr28** [comment]
Fixed.
