### ISSUE TITLE
bestbuttonsandlights failing

### ISSUE THREAD

**Issue by arr28** [SanchoGGP/ggp-base#284]
In builds 211, 212, 213, 215 & 216, we failed stanford.bestbuttonsandlights.  (It passed in 214, so is at least somewhat intermittent.)

Looking at the logs from 215, there are a few points to note.

1. We first mark the root complete during meta-gaming.  It's a complete win.
2. We don't cache a plan.  There's presumably due to #249.  No need to consider that here. 
3. Interestingly, we mark the root complete 9 times within 2ms - all scoring 100.  This is presumably because the game is factored into 9 pieces.  Interesting that we consider all roots to be worth 100.
4. On each of the remaining turns, we mark 8 roots as complete losses, but don't mark the complete win root.
5. **Whenever we log the good path, it stops 2 moves short (i.e. does a9 b9 c9 a9).** This smacks of the problem that Steve previously fixed for another puzzle.
6. At move 5, we search again.  This time, we log 8 losing roots + 1 winning root.  On this occasion, we do cache a (correct) plan.
7. **At move 6, we play a pre-planned move (a9) but also seem to run the GameSearcher which promptly crashes**.  My guess here is that, because we've selected a move, we're searching from that state, without realising it's terminal.

```
2015-06-02 14:29:51,490 INFO  Sancho                         Starting turn 6
2015-06-02 14:29:51,490 DEBUG Sancho                         Calculating current state
2015-06-02 14:29:51,490 INFO  Sancho                         Playing pre-planned move: ( a 9 )
2015-06-02 14:29:51,490 INFO  GameSearcher                   MCTS iterations last turn = 24
2015-06-02 14:29:51,490 DEBUG GameSearcher                   Start move search...
2015-06-02 14:29:51,490 INFO  TreeNode                       Free all but rooted in state: ( ( true ( step 6 ) ) )
2015-06-02 14:29:51,490 INFO  TreeNode                       Freed 5% of allocated nodes (2 of 34)
2015-06-02 14:29:51,490 INFO  MCTSTree                       Complete root has no known child path - marking incomplete to force re-expansion
2015-06-02 14:29:51,490 INFO  MCTSTree                       Encountered childless root - must re-expand
2015-06-02 14:29:51,494 INFO  GameSearcher                   Terminating GameSearcher
2015-06-02 14:29:51,490 ERROR StateMachineGamer              Exception in player during move selection
java.lang.NullPointerException
	at org.ggp.base.player.gamer.statemachine.sancho.TreeNode.calculateTerminalityAndAutoExpansion(TreeNode.java:2336) ~[bin/:?]
	at org.ggp.base.player.gamer.statemachine.sancho.TreeNode.expandInternal(TreeNode.java:3384) ~[bin/:?]
	at org.ggp.base.player.gamer.statemachine.sancho.TreeNode.expand(TreeNode.java:2586) ~[bin/:?]
	at org.ggp.base.player.gamer.statemachine.sancho.MCTSTree.setRootState(MCTSTree.java:773) ~[bin/:?]
	at org.ggp.base.player.gamer.statemachine.sancho.GameSearcher.startSearch(GameSearcher.java:872) ~[bin/:?]
	at org.ggp.base.player.gamer.statemachine.sancho.Sancho.stateMachineSelectMove(Sancho.java:1264) ~[bin/:?]
	at org.ggp.base.player.gamer.statemachine.StateMachineGamer.selectMove(StateMachineGamer.java:248) [bin/:?]
	at org.ggp.base.player.request.grammar.PlayRequest.process(PlayRequest.java:58) [bin/:?]
	at org.ggp.base.test.PuzzleBase.getResponse(PuzzleBase.java:236) [bin/:?]
	at org.ggp.base.test.PuzzleBase.testPuzzle(PuzzleBase.java:183) [bin/:?]
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_31]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47) [junit-4.11.jar:?]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.11.jar:?]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44) [junit-4.11.jar:?]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.11.jar:?]
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) [junit-4.11.jar:?]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271) [junit-4.11.jar:?]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70) [junit-4.11.jar:?]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50) [junit-4.11.jar:?]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238) [junit-4.11.jar:?]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63) [junit-4.11.jar:?]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236) [junit-4.11.jar:?]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53) [junit-4.11.jar:?]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229) [junit-4.11.jar:?]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309) [junit-4.11.jar:?]
	at org.junit.runners.Suite.runChild(Suite.java:127) [junit-4.11.jar:?]
	at org.junit.runners.Suite.runChild(Suite.java:26) [junit-4.11.jar:?]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238) [junit-4.11.jar:?]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63) [junit-4.11.jar:?]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236) [junit-4.11.jar:?]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53) [junit-4.11.jar:?]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229) [junit-4.11.jar:?]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309) [junit-4.11.jar:?]
	at junit.framework.JUnit4TestAdapter.run(JUnit4TestAdapter.java:38) [junit-4.11.jar:?]
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:532) [ant-junit.jar:?]
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.launch(JUnitTestRunner.java:1179) [ant-junit.jar:?]
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:1030) [ant-junit.jar:?]
```

Likely only reproducible when CPU_INTENSIVE_THREADS=1 (or perhaps 2).  Worth fixing (7) before addressing (5).

**Comment by SteveDraper** [comment]
Point (5) is actually fine.  Because the node is complete (inferred from greedy rollout result at depth <2) there are never any children generated, and the 'expected path' logs are just what is within the tree scope.  There is an in-principal bug (though not one that impacts this game) in that the processing of completed rollouts that find completions like this do not result in plan caching, which I will fix.  However, this has no impact in this game because it is factored, and we anyway do not cache plans for factored games.

**Comment by arr28** [comment]
There's something not quite true in that analysis.  Here are my complete logs from running stanford.bestbuttonsandlights locally a few minutes ago.  It shows both that we recognise it as having 9 factors and that we cache a plan.

```
21:14:33.966 - ======================================================
21:14:33.967 - Beginning new game: Base.bestbuttonsandlights.1433621673918
21:14:33.967 - Logs available at:  http://localhost:9199/localview/Base.bestbuttonsandlights.1433621673918
21:14:34.035 - Looks like a game of stanford.bestbuttonsandlights
21:14:34.070 - Starting watchdog with interval 600000ms
21:14:34.469 - Animator instance state vector size: 165
21:14:34.477 - Game appears to factorize into 9 factors
21:14:34.490 - Reducing with respect to XSentence: ( true ( step 3 ) )
21:14:34.543 - Num components in goal-less X-net: 269
21:14:34.543 - Num components in goal-less O-net: 270
21:14:34.543 - Num components in goal net:        44
21:14:34.545 - Animator instance state vector size: 165
21:14:34.548 - Animator instance state vector size: 165
21:14:34.549 - Animator instance state vector size: 21
21:14:34.550 - This is Sancho 1.60v with last commit d188eec8c7d972b4545311c0fc2611c776753015
21:14:34.551 - Running with machine-specific properties:
21:14:34.551 - 	SAFETY_MARGIN = 3300 (default: 2500)
21:14:34.551 - 	WC_LOCATION = C:/Personal/Projects/GGP/ggp-base (default: null)
21:14:34.551 - 	CPU_INTENSIVE_THREADS = 1 (default: -1)
21:14:34.551 - 	USE_AFFINITY = false (default: true)
21:14:34.552 - 	DISABLE_LEARNING = true (default: false)
21:14:34.565 - Start clock: 30s
21:14:34.565 - Play clock:  15s
21:14:34.565 - We are:      robot
21:14:34.567 - No positive goal latches
21:14:34.567 - No negative goal latches
21:14:34.568 - Not suitable for PayoffMatrixGamePlayer: Not a 2-player game
21:14:46.809 - No heuristics enabled
21:14:46.809 - Performed 258355 simulations to calculate heuristics
21:14:52.046 - branchingFactorApproximation = 27.0, averageBranchingFactor = 27.0, choices high water mark = 27
21:14:52.046 - Did 13983 simulations for game characteristics
21:14:52.046 - Fixed characteristics
21:14:52.046 -   Game is a pseudo puzzle
21:14:52.046 -   Game is not a simultaneous turn game
21:14:52.046 -   Game is a 1-player puzzle
21:14:52.046 - Statistical characteristics
21:14:52.046 -   Range of lengths of sample games seen:          [5,6]
21:14:52.046 -   Average num turns:                              5.0
21:14:52.046 -   Std deviation num turns:                        0.0
21:14:52.046 -   Average num turns for non-drawn result:         5.0
21:14:52.046 -   Goals stability:                                1.0
21:14:52.046 -   Proportion of max length games ending in draws: 0.0
21:14:52.046 -   Num factors:                                    9
21:14:52.046 -   Max factor failure time (ms)                    0
21:14:52.046 -   IsFixedSum                                      false
21:14:52.046 - Set explorationBias range to [0.96, 1.44]
21:14:52.047 - Greedy rollout terminal discovery effectiveness: 2.307076495735369E-4
21:14:52.047 - Num terminal props seen: 27 out of 34
21:14:52.047 - Estimated greedy rollout cost: 26.999937708934617
21:14:52.047 - Min raw score = 0, max = 100
21:14:52.047 - multiRoleAverageScoreDiff = 0
21:14:52.047 - Game is a puzzle so not normalizing scores
21:14:52.047 - Performed 13983 simulations in 5237ms
21:14:52.047 - 2670 simulations/second performed - setting rollout sample size to 1
21:14:54.045 - Iterations in 999 ms with/without removal before adding: 2772/2666
21:14:54.045 - Speed improvement insufficient to justify 2-pass prop setting
21:14:54.049 - Weight decay disabled
21:14:54.050 - Using periodic node score normalization
21:14:54.050 - Using UCB-tuned
21:14:54.050 - Early cutoff disabled
21:14:54.052 - Weight decay disabled
21:14:54.052 - Using periodic node score normalization
21:14:54.052 - Using UCB-tuned
21:14:54.052 - Early cutoff disabled
21:14:54.052 - Weight decay disabled
21:14:54.052 - Using periodic node score normalization
21:14:54.052 - Using UCB-tuned
21:14:54.052 - Early cutoff disabled
21:14:54.052 - Weight decay disabled
21:14:54.053 - Using periodic node score normalization
21:14:54.053 - Using UCB-tuned
21:14:54.053 - Early cutoff disabled
21:14:54.053 - Weight decay disabled
21:14:54.053 - Using periodic node score normalization
21:14:54.053 - Using UCB-tuned
21:14:54.053 - Early cutoff disabled
21:14:54.053 - Weight decay disabled
21:14:54.053 - Using periodic node score normalization
21:14:54.053 - Using UCB-tuned
21:14:54.053 - Early cutoff disabled
21:14:54.053 - Weight decay disabled
21:14:54.053 - Using periodic node score normalization
21:14:54.053 - Using UCB-tuned
21:14:54.053 - Early cutoff disabled
21:14:54.053 - Weight decay disabled
21:14:54.053 - Using periodic node score normalization
21:14:54.053 - Using UCB-tuned
21:14:54.053 - Early cutoff disabled
21:14:54.054 - Weight decay disabled
21:14:54.054 - Using periodic node score normalization
21:14:54.054 - Using UCB-tuned
21:14:54.054 - Early cutoff disabled
21:14:54.054 - This game is not suitable for local search
21:14:54.133 - MCTS iterations last turn = 0
21:14:54.133 - Encountered childless root - must re-expand
21:14:54.134 - Root has 4 children, and is not complete
21:14:54.134 - Encountered childless root - must re-expand
21:14:54.134 - Root has 4 children, and is not complete
21:14:54.134 - Encountered childless root - must re-expand
21:14:54.134 - Root has 4 children, and is not complete
21:14:54.134 - Encountered childless root - must re-expand
21:14:54.134 - Root has 4 children, and is not complete
21:14:54.134 - Encountered childless root - must re-expand
21:14:54.134 - Root has 4 children, and is not complete
21:14:54.134 - Encountered childless root - must re-expand
21:14:54.134 - Root has 4 children, and is not complete
21:14:54.134 - Encountered childless root - must re-expand
21:14:54.134 - Root has 4 children, and is not complete
21:14:54.134 - Encountered childless root - must re-expand
21:14:54.134 - Root has 4 children, and is not complete
21:14:54.134 - Encountered childless root - must re-expand
21:14:54.134 - Root has 4 children, and is not complete
21:14:54.136 - Move search started
21:14:54.136 - Starting sample size update timer
21:14:54.188 - Cached new best plan: [( a 9 ), ( b 9 ), ( c 9 ), ( a 9 ), ( b 9 ), ( a 9 )]
21:14:54.188 - Mark root complete
21:14:54.190 - Mark root complete
21:14:54.191 - Mark root complete
21:14:54.192 - Mark root complete
21:14:54.194 - Mark root complete
21:14:54.195 - Mark root complete
21:14:54.195 - Mark root complete
21:14:54.196 - Mark root complete
21:14:54.197 - Mark root complete
21:14:54.197 - Move search complete
21:14:54.384 - Early search termination because root is complete
21:14:54.384 - Ready to play
21:14:54.408 - Starting turn 1
21:14:54.408 - Playing pre-planned move: ( a 9 )
21:14:54.423 - Moves played for turn 1: [( a 9 )]
21:14:54.423 - Non-null move last turn was: ( a 9 )
21:14:54.423 - Starting turn 2
21:14:54.423 - Playing pre-planned move: ( b 9 )
21:14:54.435 - Moves played for turn 2: [( b 9 )]
21:14:54.435 - Non-null move last turn was: ( b 9 )
21:14:54.435 - Starting turn 3
21:14:54.435 - Playing pre-planned move: ( c 9 )
21:14:54.447 - Moves played for turn 3: [( c 9 )]
21:14:54.447 - Non-null move last turn was: ( c 9 )
21:14:54.447 - Starting turn 4
21:14:54.447 - Playing pre-planned move: ( a 9 )
21:14:54.471 - Moves played for turn 4: [( a 9 )]
21:14:54.471 - Non-null move last turn was: ( a 9 )
21:14:54.471 - Starting turn 5
21:14:54.471 - Playing pre-planned move: ( b 9 )
21:14:54.483 - Moves played for turn 5: [( b 9 )]
21:14:54.483 - Non-null move last turn was: ( b 9 )
21:14:54.483 - Starting turn 6
21:14:54.483 - Playing pre-planned move: ( a 9 )
21:14:54.499 - Final score: 100
21:14:54.499 - Stop rollout processors
21:14:54.499 - Finished stopping rollout processors
21:14:54.500 - Terminating GameSearcher
21:14:54.609 - Tlkio thread terminated
21:14:54.609 - Stop the watchdog
21:14:54.610 - Watchdog terminated
21:14:57.652 - Tidy-up complete
```

**Comment by arr28** [comment]
I've committed a fix for (7).  I've also managed to repro the above scenario locally (by setting CPU_INTENSIVE_THREADS=1 and turning down start clock to 15).  It no longer crashes after deciding the last move.  It does still show root completion without a caching a plan - which I think is what you've said you're going to fix.

Over to you.  Feel free to close when done.

**Comment by SteveDraper** [comment]
Turns out we are inconsistent about when we cache plans in relation to whether a game is factorized.  In particular we always cache a plan if we find a winning terminal state in node expansion, but do not if we find it as a result of a greedy rollout.  Since we currently only factorize games with disjunctive goal, conditions I can't see why we need to not cache (puzzle) plans for factored games, so I am removing that limitation, which explains Andrew's logs.
