### ISSUE TITLE
null ref occurred playing breakthrough

### ISSUE THREAD

**Issue by SteveDraper** [SanchoGGP/ggp-base#308]
```
java.lang.NullPointerException
	at org.ggp.base.util.propnet.polymorphic.forwardDeadReckon.ForwardDeadReckonInternalMachineState.copy(ForwardDeadReckonInternalMachineState.java:281) ~[Sancho1.60y.jar:?]
	at org.ggp.base.player.gamer.statemachine.sancho.GameSearcher.getPrimaryPath(GameSearcher.java:574) ~[Sancho1.60y.jar:?]
	at org.ggp.base.player.gamer.statemachine.sancho.GameSearcher.expandSearch(GameSearcher.java:782) ~[Sancho1.60y.jar:?]
	at org.ggp.base.player.gamer.statemachine.sancho.GameSearcher.run(GameSearcher.java:392) [Sancho1.60y.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
2015-06-30 10:17:12,515 INFO  GameSearcher                   Move search started
2015-06-30 10:17:12,515 ERROR GameSearcher                   Exception
java.lang.NullPointerException
	at org.ggp.base.util.propnet.polymorphic.forwardDeadReckon.ForwardDeadReckonInternalMachineState.copy(ForwardDeadReckonInternalMachineState.java:281) ~[Sancho1.60y.jar:?]
	at org.ggp.base.player.gamer.statemachine.sancho.GameSearcher.getPrimaryPath(GameSearcher.java:574) ~[Sancho1.60y.jar:?]
	at org.ggp.base.player.gamer.statemachine.sancho.GameSearcher.expandSearch(GameSearcher.java:782) ~[Sancho1.60y.jar:?]
	at org.ggp.base.player.gamer.statemachine.sancho.GameSearcher.run(GameSearcher.java:392) [Sancho1.60y.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
2015-06-30 10:17:12,907 INFO  LocalRegionSearcher            Performing regular search for optional role 1 at depth 10
2015-06-30 10:17:12,907 INFO  LocalRegionSearcher            Local search completed at depth 10 with 1476786 states visited
2015-06-30 10:17:12,907 INFO  LocalRegionSearcher            Performing regular search for optional role 0 at depth 11
2015-06-30 10:17:12,907 INFO  LocalRegionSearcher            Performing regular search for optional role 1 at depth 11
2015-06-30 10:17:46,057 DEBUG Sancho                         Time to submit order - ask GameSearcher to yield
2015-06-30 10:17:46,057 DEBUG GameSearcher                   Searching for best move amongst factors:
2015-06-30 10:17:46,057 WARN  TreeNode                       Unexpanded child of root for move: ( pinpoints 4 2 4 3 )
2015-06-30 10:17:46,057 WARN  TreeNode                       Unexpanded child of root for move: ( pinpoints 4 2 5 3 )
2015-06-30 10:17:46,057 WARN  TreeNode                       Unexpanded child of root for move: ( pinpoints 3 2 4 3 )
2015-06-30 10:17:46,057 WARN  TreeNode                       Unexpanded child of root for move: ( pinpoints 4 2 3 3 )
2015-06-30 10:17:46,057 WARN  TreeNode                       Unexpanded child of root for move: ( pinpoints 3 2 3 3 )
2015-06-30 10:17:46,057 WARN  TreeNode                       Unexpanded child of root for move: ( pinpoints 4 1 5 2 )
2015-06-30 10:17:46,057 WARN  TreeNode                       Unexpanded child of root for move: ( pinpoints 2 1 1 2 )
2015-06-30 10:17:46,057 WARN  TreeNode                       Unexpanded child of root for move: ( pinpoints 6 1 5 2 )
2015-06-30 10:17:46,057 WARN  TreeNode                       Unexpanded child of root for move: ( pinpoints 1 1 2 2 )
2015-06-30 10:17:46,057 WARN  TreeNode                       Unexpanded child of root for move: ( pinpoints 3 1 2 2 )
2015-06-30 10:17:46,057 WARN  TreeNode                       Unexpanded child of root for move: ( pinpoints 1 1 1 2 )
2015-06-30 10:17:46,057 WARN  TreeNode                       Unexpanded child of root for move: ( pinpoints 2 1 2 2 )
2015-06-30 10:17:46,057 WARN  TreeNode                       Unexpanded child of root for move: ( pinpoints 2 3 1 4 )
2015-06-30 10:17:46,057 WARN  TreeNode                       Unexpanded child of root for move: ( pinpoints 2 3 3 4 )
2015-06-30 10:17:46,057 WARN  TreeNode                       Unexpanded child of root for move: ( pinpoints 4 4 5 5 )
2015-06-30 10:17:46,057 WARN  TreeNode                       Unexpanded child of root for move: ( pinpoints 4 4 4 5 )
2015-06-30 10:17:46,057 WARN  TreeNode                       Unexpanded child of root for move: ( pinpoints 4 4 3 5 )
2015-06-30 10:17:46,057 WARN  TreeNode                       Unexpanded child of root for move: ( pinpoints 7 4 6 5 )
2015-06-30 10:17:46,057 WARN  TreeNode                       Unexpanded child of root for move: ( pinpoints 7 4 8 5 )
2015-06-30 10:17:46,057 WARN  TreeNode                       Unexpanded child of root for move: ( pinpoints 7 5 6 6 )
2015-06-30 10:17:46,057 WARN  TreeNode                       Unexpanded child of root for move: ( pinpoints 7 5 8 6 )
2015-06-30 10:17:46,057 WARN  TreeNode                       Unexpanded child of root for move: ( pinpoints 6 2 6 3 )
2015-06-30 10:17:46,057 WARN  TreeNode                       Unexpanded child of root for move: ( pinpoints 6 2 7 3 )
2015-06-30 10:17:46,057 WARN  TreeNode                       Unexpanded child of root for move: ( pinpoints 6 2 5 3 )
2015-06-30 10:17:46,057 WARN  TreeNode                       Unexpanded child of root for move: ( pinpoints 7 2 6 3 )
2015-06-30 10:17:46,057 WARN  TreeNode                       Unexpanded child of root for move: ( pinpoints 7 2 8 3 )
2015-06-30 10:17:46,057 WARN  TreeNode                       Unexpanded child of root for move: ( pinpoints 7 2 7 3 )
2015-06-30 10:17:46,057 WARN  TreeNode                       No move found!
```

**Comment by SteveDraper** [comment]
Actually the smoking gun is just before the above in the log:

2015-06-30 10:17:12,513 INFO  TreeNode                       Freed 99% of allocated nodes (2970011 of 2970012)
2015-06-30 10:17:12,513 INFO  MCTSTree                       Encountered childless root - must re-expand

This means it could not locate the new root state in the existing tree (though the response list to the noop on the previous move showed it as having had approx 14K visits).  This locked the tree for a few seconds while it deleted everything then rexpanded the root (leaving all children unexpanded) and then released the tree lock to allow searching to continue.  The first thing the search thread did was attempt to retrieve the primary path to give it to local search, and there is a bug there which means it doesn't cope with the no-children-expanded state, which is the proximate cause of the exception.

That part is easy to fix.  However, the bigger question is 'why was the new root state not found?', which implies a broader issue...

**Comment by arr28** [comment]
I notice that Alex updated the GDL for all the Breakthrough variants on 16th May.  See https://github.com/ggp-org/ggp-repository/commit/fa698c42033f443841dad71348160dab7cde0135 for diffs.  The only change affecting Breakthrough seems to be that inputs are more tightly specified although I don't completely understand what he has done.

Probably not relevant here.

**Comment by SteveDraper** [comment]
Cause appears to have been the playing of an unexpected response in a game with long time limits, resulting in mostly full node table most of the time.  Such conditions lead to lots of trimming, and the current trimming algorithm tends to empty out entire sub-trees back to the root's immediate children.  When such a child is chosen it results in a new root that is unexpanded and can result in the observed exception.

Although the trimming algorithm could probably be improved, trimming an 'unlikely' branch is anyway not a major issue, since it will have been only lightly explored, so not much information is lost when it actually gets selected.  As such the consequential crash is the only thing that really needs fixing here.
