### ISSUE TITLE
Crash on stanford.multiplehunter

### ISSUE THREAD

**Issue by arr28** [SanchoGGP/ggp-base#320]
We reliably crash (during MG) on stanford.multiplehunter.  We've seen a few problems in this location recently.  The most recent was because we weren't reloading factors correctly.  However, this problem is seen even with learning disabled.

Steve - please could you take a look, because I suspect this is fairly straightforward for you to knock off.  If you manage to fix it, please search for "multiplehunter" in `PuzzleBase` and remove it from the `SKIP` set.

```
16:42:13.999 ! Exception
java.lang.NullPointerException
	at org.ggp.base.util.statemachine.implementation.propnet.forwardDeadReckon.ForwardDeadReckonPropnetStateMachine.transitionToRandomJointMove(ForwardDeadReckonPropnetStateMachine.java:4058) ~[bin/:?]
	at org.ggp.base.util.statemachine.implementation.propnet.forwardDeadReckon.ForwardDeadReckonPropnetStateMachine.getDepthChargeResult(ForwardDeadReckonPropnetStateMachine.java:4382) ~[bin/:?]
	at org.ggp.base.player.gamer.statemachine.sancho.RolloutRequest.process(RolloutRequest.java:97) ~[bin/:?]
	at org.ggp.base.player.gamer.statemachine.sancho.TreeNode.rollOut(TreeNode.java:5862) ~[bin/:?]
	at org.ggp.base.player.gamer.statemachine.sancho.MCTSTree.selectAction(MCTSTree.java:1047) ~[bin/:?]
	at org.ggp.base.player.gamer.statemachine.sancho.MCTSTree.growTree(MCTSTree.java:832) ~[bin/:?]
	at org.ggp.base.player.gamer.statemachine.sancho.GameSearcher.expandSearch(GameSearcher.java:841) ~[bin/:?]
	at org.ggp.base.player.gamer.statemachine.sancho.GameSearcher.run(GameSearcher.java:396) [bin/:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_40]
```

**Comment by arr28** [comment]
FWIW, I think that the regular factor analysis might be computing an invalid control set.  It contains lots of blank cell props - e.g. `( true ( cell 8 2 1 blank ) )` which seems unlikely (but not impossible) to me.

Once fixed, please also remove from the `SKIP` set in `KnownGameTest` (and commit the characteristics so that the test passes).

**Comment by SteveDraper** [comment]
I am unable to reproduce a problem.  It reliably solves to a final score of 87 (which is the best possible) in about 1 second for me (with learning on or off).  Also the control set is fine - it just reflects 'dead' propositions that have no impact and which it includes in the control set because they are not influenced by player moves (once irrelevant moves have been trimmed)

**Comment by arr28** [comment]
Don't know what was going on earlier, but it's certainly fine now.  (With and without learning.)

**Comment by SteveDraper** [comment]
Still crashing on SanpCI.  Single threaded run perhaps makes the difference (will investigate)...

**Comment by SteveDraper** [comment]
Issue was that for games that use the goals net for evaluating legals (very few do,m but it seems multiplehunter does), then the application of a policy that sometimes rejects moves fails on state machine instance 0 (only, since that's the only one that uses the goals net in this way, as it's an MCTS expansion-oriented optimization).  State machine instance 0 is typically used for playouts only when there is only one thread - hence the observed behaviour.

**Comment by arr28** [comment]
Steve - passing to you since I think you're looking into this.  (Indeed, you might have solved it, in which case you can just close it.)

**Comment by SteveDraper** [comment]
Indeed - fixed it last night.
