### ISSUE TITLE
Crash in stanford.go

### ISSUE THREAD

**Issue by arr28** [SanchoGGP/ggp-base#321]
We crash during propnet construction for stanford.go.  The GDL for this game post-dates the 2014 competition.  Perhaps they plan to use it this year?

```
[GamePlayer] java.lang.NullPointerException
	at org.ggp.base.util.gdl.model.SentenceFormsFinder$TermModel.mergeIn(SentenceFormsFinder.java:436)
	at org.ggp.base.util.gdl.model.SentenceFormsFinder$TermModel.addTerm(SentenceFormsFinder.java:490)
	at org.ggp.base.util.gdl.model.SentenceFormsFinder.addBodyToModel(SentenceFormsFinder.java:406)
	at org.ggp.base.util.gdl.model.SentenceFormsFinder.addSentenceToModel(SentenceFormsFinder.java:378)
	at org.ggp.base.util.gdl.model.SentenceFormsFinder.addTrueSentencesToModel(SentenceFormsFinder.java:358)
	at org.ggp.base.util.gdl.model.SentenceFormsFinder.createModel(SentenceFormsFinder.java:64)
	at org.ggp.base.util.gdl.model.SentenceFormsFinder.findSentenceForms(SentenceFormsFinder.java:45)
	at org.ggp.base.util.gdl.model.SentenceFormModelFactory.getSentenceForms(SentenceFormModelFactory.java:210)
	at org.ggp.base.util.gdl.model.SentenceFormModelFactory.create(SentenceFormModelFactory.java:39)
	at org.ggp.base.util.gdl.transforms.VariableConstrainer.replaceFunctionValuedVariables(VariableConstrainer.java:72)
	at org.ggp.base.util.propnet.polymorphic.factory.OptimizingPolymorphicPropNetFactory.create(OptimizingPolymorphicPropNetFactory.java:130)
	at org.ggp.base.util.statemachine.implementation.propnet.forwardDeadReckon.ForwardDeadReckonPropnetStateMachine.initialize(ForwardDeadReckonPropnetStateMachine.java:1625)
	at org.ggp.base.player.gamer.statemachine.sancho.StateMachineProxy.initialize(StateMachineProxy.java:38)
	at org.ggp.base.player.gamer.statemachine.StateMachineGamer.metaGame(StateMachineGamer.java:204)
	at org.ggp.base.player.request.grammar.StartRequest.process(StartRequest.java:70)
	at org.ggp.base.player.GamePlayer.run(GamePlayer.java:111)
```

**Comment by arr28** [comment]
Invalid GDL.

```
Validator: Unsafe rule ( <= ( distinctcell ?n ?m ?p ?q ) ( not ( eq ?p ?n ) ) )
Variable ?n is not defined in a positive relation in the rule's body
```

No need for us to deal with this.
