### ISSUE TITLE
Crash in stanford.zertz

### ISSUE THREAD

**Issue by arr28** [SanchoGGP/ggp-base#323]
During propnet construction...

```
17:42:23.235 ! Exception in player during meta-gaming
java.lang.IllegalStateException: var is ?px;
varDomains key set is [?x, ?y];
varsInHead is [];
rule is ( <= ( legal red noop ) ( true ( jumped red ?x ?y ) ) ( not ( legal red ( jump ?px ?py ?rx ?ry ?ax ?ay ?col ) ) ) )
	at org.ggp.base.util.gdl.model.SentenceDomainModelOptimizer.applyRuleBodyOnlyPropagation(SentenceDomainModelOptimizer.java:368) ~[bin/:?]
	at org.ggp.base.util.gdl.model.SentenceDomainModelOptimizer.propagateNeededConstants(SentenceDomainModelOptimizer.java:335) ~[bin/:?]
	at org.ggp.base.util.gdl.model.SentenceDomainModelOptimizer.removeUnneededConstants(SentenceDomainModelOptimizer.java:302) ~[bin/:?]
	at org.ggp.base.util.gdl.model.SentenceDomainModelOptimizer.restrictDomainsToUsefulValues(SentenceDomainModelOptimizer.java:79) ~[bin/:?]
	at org.ggp.base.util.gdl.transforms.CondensationIsolator.run(CondensationIsolator.java:136) ~[bin/:?]
	at org.ggp.base.util.propnet.polymorphic.factory.OptimizingPolymorphicPropNetFactory.create(OptimizingPolymorphicPropNetFactory.java:132) ~[bin/:?]
	at org.ggp.base.util.statemachine.implementation.propnet.forwardDeadReckon.ForwardDeadReckonPropnetStateMachine.initialize(ForwardDeadReckonPropnetStateMachine.java:1625) ~[bin/:?]
	at org.ggp.base.player.gamer.statemachine.sancho.StateMachineProxy.initialize(StateMachineProxy.java:38) ~[bin/:?]
	at org.ggp.base.player.gamer.statemachine.StateMachineGamer.metaGame(StateMachineGamer.java:204) [bin/:?]
	at org.ggp.base.player.request.grammar.StartRequest.process(StartRequest.java:70) [bin/:?]
	at org.ggp.base.player.GamePlayer.run(GamePlayer.java:111) [bin/:?]
```

**Comment by arr28** [comment]
Invalid GDL.

```
Validator: Unsafe rule ( <= ( legal red noop ) ( true ( jumped red ?x ?y ) ) ( not ( legal red ( jump ?px ?py ?rx ?ry ?ax ?ay ?col ) ) ) )
Variable ?px is not defined in a positive relation in the rule's body
```

No need for us to deal with this.
