### ISSUE TITLE
Exception in meta-gaming

### ISSUE THREAD

**Issue by arr28** [SanchoGGP/ggp-base#338]
Playing base.connectfour...

```
21:32:02.173 - Completed analysing move distances...
21:32:02.179 - Using RAVE
21:32:02.179 - MCTS iterations last turn = 0
21:32:02.179 - Encountered childless root - must re-expand
21:32:02.179 - Root has 8 children, and is not complete
21:32:02.179 - Move search started
21:32:02.179 - Starting sample size update timer
21:32:03.206 ! Exception
java.lang.NullPointerException
	at org.ggp.base.player.gamer.statemachine.sancho.TreeNode.updateStats(TreeNode.java:6105) ~[bin/:?]
	at org.ggp.base.player.gamer.statemachine.sancho.GameSearcher.processCompletedRollout(GameSearcher.java:1201) ~[bin/:?]
	at org.ggp.base.player.gamer.statemachine.sancho.GameSearcher.processCompletedRollouts(GameSearcher.java:1261) ~[bin/:?]
	at org.ggp.base.player.gamer.statemachine.sancho.GameSearcher.expandSearch(GameSearcher.java:935) ~[bin/:?]
	at org.ggp.base.player.gamer.statemachine.sancho.GameSearcher.run(GameSearcher.java:415) [bin/:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
21:32:03.717 - Ready to play
21:32:03.957 - Starting turn 1
21:32:03.957 - MCTS iterations last turn = 5679
21:32:03.957 - Root has 8 children, and is not complete
21:32:03.957 - Move search started
```

We seemed to recover and win (against Random).

**Comment by arr28** [comment]
Version was...

```
2015-07-14 21:31:37,700 INFO  Sancho                         This is Sancho 1.60z with last commit 6bd321552cca232e7936ca290232cd2a424d6d84
```

**Comment by arr28** [comment]
NPE was hit on the line that sets up `canonicalIndex` in...

```java
                    if ( parentMoveInfo.mMasterIndex == moveInfo.mMasterIndex )
                    {
                      int canonicalIndex = (ancestor.mPrimaryChoiceMapping == null ? ancestorIndex : ancestor.mPrimaryChoiceMapping[ancestorIndex]);

                      //  Put a ceiling on the weight of the pre-warm value from the parent so that we converge using
                      //  local data quickly without the parewnt hint having too much momentum
                      lNode.mRAVEStats.mCounts[lii] = Math.min(ancestor.mRAVEStats.mCounts[canonicalIndex], 5);
                      lNode.mRAVEStats.mScores[lii] = ancestor.mRAVEStats.mScores[canonicalIndex];
                    }
```

**Comment by SteveDraper** [comment]
Are you sure you didn't have any local modifications at the time, because
that simply looks impossible.  The only way that line could null ref is if
ancestor == null, but that is explicitly checked just above

**Comment by arr28** [comment]
If I had local modifications then presumably they would have been my next check-in (which I made ~40mins after hitting this, so quite likely).  That would make the relevant line the one which sets up `parentMoveInfo` in the following.

```
                  for(int lij = 0; lij < ancestor.mNumChildren; lij++, ancestorIndex = (ancestorIndex + 1)%ancestor.mNumChildren)
                  {
                    Object lParentChoice = ancestor.mChildren[ancestorIndex];
                    ForwardDeadReckonLegalMoveInfo parentMoveInfo = (lParentChoice instanceof TreeEdge) ? ((TreeEdge)lParentChoice).mPartialMove : (ForwardDeadReckonLegalMoveInfo)lParentChoice;

                    if ( parentMoveInfo.mMasterIndex == moveInfo.mMasterIndex )
                    {
                      int canonicalIndex = (ancestor.mPrimaryChoiceMapping == null ? ancestorIndex : ancestor.mPrimaryChoiceMapping[ancestorIndex]);

                      //  Put a ceiling on the weight of the pre-warm value from the parent so that we converge using
                      //  local data quickly without the parewnt hint having too much momentum
                      lNode.mRAVEStats.mCounts[lii] = Math.min(ancestor.mRAVEStats.mCounts[canonicalIndex], 5);
                      lNode.mRAVEStats.mScores[lii] = ancestor.mRAVEStats.mScores[canonicalIndex];
                    }
                  }
```

**Comment by SteveDraper** [comment]
Right, which is precisely the case the deleteEdge() bug would explain, so I
think I'll stick with that explanation ;-)
