### ISSUE TITLE
Propnet optimization failure for Hitori

### ISSUE THREAD

**Issue by arr28** [SanchoGGP/ggp-base#357]
```
2015-08-14 11:22:12,304 DEBUG izingPolymorphicPropNetFactory Building propnet
2015-08-14 11:22:13,310 DEBUG dDeadReckonPropnetStateMachine Num components after anon prop removal: 3984
2015-08-14 11:22:13,459 INFO  StdOutErrLog                   Exception in thread "GamePlayer - Sancho 1.61c (9147)" 
2015-08-14 11:22:13,460 INFO  StdOutErrLog                   java.lang.StackOverflowError
2015-08-14 11:22:13,463 INFO  StdOutErrLog                   	at org.ggp.base.util.propnet.polymorphic.factory.OptimizingPolymorphicPropNetFactory.supportsRequiredComponentInternal(OptimizingPolymorphicPropNetFactory.java:1943)
2015-08-14 11:22:13,464 INFO  StdOutErrLog                   	at org.ggp.base.util.propnet.polymorphic.factory.OptimizingPolymorphicPropNetFactory.supportsRequiredComponentInternal(OptimizingPolymorphicPropNetFactory.java:1945)
2015-08-14 11:22:13,464 INFO  StdOutErrLog                   	at org.ggp.base.util.propnet.polymorphic.factory.OptimizingPolymorphicPropNetFactory.supportsRequiredComponentInternal(OptimizingPolymorphicPropNetFactory.java:1945)
2015-08-14 11:22:13,465 INFO  StdOutErrLog                   	at org.ggp.base.util.propnet.polymorphic.factory.OptimizingPolymorphicPropNetFactory.supportsRequiredComponentInternal(OptimizingPolymorphicPropNetFactory.java:1945)
2015-08-14 11:22:13,465 INFO  StdOutErrLog                   	at org.ggp.base.util.propnet.polymorphic.factory.OptimizingPolymorphicPropNetFactory.supportsRequiredComponentInternal(OptimizingPolymorphicPropNetFactory.java:1945)

<~1000 times>
```

**Comment by arr28** [comment]
I can't create a version of Hitori than any player/server is happy with.  (I suspect it would need Hex-style connection detection for the blacked out cells.)

Closing this.
