### ISSUE TITLE
Crash in stanford.hunter & others (recent regression)

### ISSUE THREAD

**Issue by arr28** [SanchoGGP/ggp-base#377]
Several games, including stanford.hunter, crash during meta-gaming with the exception below.  This was caused by the block of changes from 2eaac135da6f327b64e62054ef30abdb1a4536ed to 7e0b2a31881a04b8748b514b290f2b7cd2e4ec62.

Steve, are you able to take a look?

```
[GamePlayer] java.lang.NullPointerException
	at org.ggp.base.util.statemachine.implementation.propnet.forwardDeadReckon.ForwardDeadReckonPropnetStateMachine.transitionToRandomJointMove(ForwardDeadReckonPropnetStateMachine.java:3674)
	at org.ggp.base.util.statemachine.implementation.propnet.forwardDeadReckon.ForwardDeadReckonPropnetStateMachine.getDepthChargeResult(ForwardDeadReckonPropnetStateMachine.java:3923)
	at org.ggp.base.util.statemachine.implementation.propnet.forwardDeadReckon.ForwardDeadReckonPropnetStateMachine.optimizeStateTransitionMechanism(ForwardDeadReckonPropnetStateMachine.java:1723)
	at org.ggp.base.player.gamer.statemachine.sancho.Sancho.stateMachineMetaGame(Sancho.java:1145)
	at org.ggp.base.player.gamer.statemachine.StateMachineGamer.metaGame(StateMachineGamer.java:208)
	at org.ggp.base.player.request.grammar.StartRequest.process(StartRequest.java:70)
	at org.ggp.base.player.GamePlayer.run(GamePlayer.java:111)
```

**Comment by arr28** [comment]
Affected games include, at least, the following Stanford games.

- arithmetic-stupid
- hunter
- hunterbig
- multiplehunter
- rainbow

*Probably* also the cause of knightstourbig going wrong, but by no means certain.

Somewhere along the lines, the following have also gone wrong, but quite possibly not related.

- selectivesukoshi
- sudoku

**Comment by SteveDraper** [comment]
Overly naive test in an earlier fix (doh!).  Trivially tightened up and the above games now all solve ok apart from Rainbow, which bombs out initializing the tri-state analysis...

**Comment by SteveDraper** [comment]
Rainbow's problem was that it has no init prop, and the tri-state analysis tripped over that.  Trivial fix, and Rainbow now also solves ok.
